### ISSUE TITLE
data_centre parameters in log_util are hard-coded

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/autonomous_patrolling#112]
log_util.py assumes the data_centre to be running at a fixed port, which is not always correct. This currently prevents the jenkins patrol job to succeed, as there the data_centre is running at a different port. log_util should get the port from the param server.

**Comment by cburbridge** [comment]
log_util does not depend on ros, so could be getting used in a script running on a non ROS machine. The problem is in waypoint_patroller/scripts/log_services.py; here the StatGenerator object should be constructed with the host and port as the parameters, not the defaults. ie create the StatGenerator like this:

```
StatGenerator(rospy.get_param("datacentre_host", "localhost"),
                     int(rospy.get_param("datacentre_port")))
``
```
