### ISSUE TITLE
error: Couldn't open joystick /dev/js1

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/autonomous_patrolling#33]
We are trying to get our new Logitech F710 running. Turtlebot_teleop has been installed and jstest js1 shows the input commands on the terminal. However, when trying to run the scitos launch file it complains about not being able to open the joystick. Rostopic list shows the /joy topic but without any output on rostopic echo...
Any ideas maybe?

strands@scitos:~$ roslaunch scitos_teleop teleop_joystick.launch 
... logging to /localhome/strands/.ros/log/6221dab0-ff67-11e2-9d4f-6c8814462a8c/roslaunch-scitos-12247.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://scitos:48006/
# SUMMARY

PARAMETERS
- /joystick/autorepeat_rate
- /joystick/dev
- /rosdistro
- /rosversion
- /teleop_base/scale_angular
- /teleop_base/scale_linear

NODES
  /
    joystick (joy/joy_node)
    teleop_base (scitos_teleop/teleop_base)
    teleop_head (scitos_teleop/head_teleop.py)
    teleop_joystick (scitos_teleop/rumble_control)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[joystick-1]: started with pid [12295]
[ERROR] [1375883059.610523180]: Couldn't open joystick /dev/js1. Will retry every second.
process[teleop_joystick-2]: started with pid [12320]
process[teleop_base-3]: started with pid [12343]
process[teleop_head-4]: started with pid [

**Comment by cdondrup** [comment]
This is not really an issue of autonomous patrolling (joystick control has been moved to scitos_apps/scitos_teleop since the we coded it at the coding camp) but I think I know what's wrong. The standard set-up of the robot when it was shipped was that the joystick would be available at /dev/js1. This is not a real standard behaviour of Ubuntu so after installing 64bit the joystick will be available at /dev/input/js1. Try `export JOYSTICK_DEVICE=/dev/input/js1` and then run the launch file again if it works, you can also add that to the .bashrc.

**Comment by cdondrup** [comment]
Another possibility is to use the udev rule created by Chris.
- Copy `scitos_apps/scitos_teleop/udev/73-persistent-joystick.rules` to `/etc/udev/rules.d/`
- Run in terminal `export JOYSTICK_DEVICE=/dev/input/rumblepad`

This ensures that you can always access the rumblepad and do not have to worry which of the `/dev/input/js*`'s is the joystick and which is the touchscreen. Once again just add the `export JOYSTICK_DEVICE=/dev/input/rumblepad` to the .bashrc.
I think this would be the best solution.

**Comment by ToMadoRe** [comment]
Great, thanks.
Do you also know what causes the error:
[ERROR] [1375884213.467160840]: Failed to call service /emergency_stop

It might be because I am not sure if I did everything correct with the scitos_mira package. Can't find any folder scitos_mira/devel/setup.bash as stated in the readme. I tried to run roslaunch scitos_mira scitos_mira.launch, which dies after outputting some errors.

**Comment by cdondrup** [comment]
This is because the scitos_node is not running. How did you set-up your robot?
Have you done this: https://github.com/strands-project/strands_systems/blob/master/README.md ? Because then you can just run `roslaunch scitos_bringup scitos.launch` and in another terminal `roslaunch scitos_teleop teleop_joystick.launch`.
I hope you did not follow the instructions in the scitos_teleop package to install it because it is very outdated. Will fix.

**Comment by ToMadoRe** [comment]
Yes, I followed the right instructions then... But there is still the same problem even when launching scitos.launch from scitos_bringup package.

It shows some errors when running the scitos.launch file, e.g.:
:
[ INFO] [1375886903.940193940]: Attempting to connect to /dev/ttyS0...
Could not open serial device /dev/ttyS0
[ERROR] [1375886903.940306918]: Could not connect to pan/tilt unit [/dev/ttyS0]
:
SerialCommS300: unable to open serial port /dev/ttyUSB0
[ptu-4] process has died [pid 2768, exit code 255, cmd /opt/strands/strands_catkin_ws/devel/lib/flir_pantilt_d46/ptu_d46 __name:=ptu __log:=/localhome/strands/.ros/log/67dd63da-ff70-11e2-866f-6c8814462a8c/ptu-4.log].
log file: /localhome/strands/.ros/log/67dd63da-ff70-11e2-866f-6c8814462a8c/ptu-4*.log
:
SerialCommS300: unable to open serial port /dev/ttyUSB0
[ERROR   ] 2013-Aug-07 16:50:04.191336 /robot/can/CANDriver Exception while invoking Runnable: Permission denied
[ERROR   ] 2013-Aug-07 16:50:04.191494 Exception:
[boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::system::system_error>] Permission denied
:
 INFO] [1375887004.569466004]: No matching device found.... waiting for devices. Reason: openni_wrapper::OpenNIDevice::OpenNIDevice(xn::Context&, const xn::NodeInfo&, const xn::NodeInfo&, const xn::NodeInfo&, const xn::NodeInfo&) @ /tmp/buildd/ros-groovy-openni-camera-1.8.9-0precise-20130724-2247/src/openni_device.cpp @ 61 : creating depth generator failed. Reason: USB interface is not supported!
: 
SerialCommS300: unable to open serial port /dev/ttyUSB0
:

**Comment by cdondrup** [comment]
It gets a bit of topic now but still:
It looks like you don't have the right permissions. Try `id` in a terminal and if you don't find `dialout` among the groups then this might be the reason. Just run `sudo usermod -a -G dialout strands` if strands is your user name. Afterwards you have to log out and back in again. Run `id` again you should see `dialout` among the groups now. Hope this fixes the usb issue because I can't really check it at the moment.

About the error shown regarding the OpenNIDevice please follow the troubleshooting instructions here: https://github.com/strands-project/vision/blob/master/README.md but beware of the typo: It's GlobalDefaults.ini not Globaldefaults.ini
Also have a look at: https://github.com/strands-project/scitos_robot/wiki/Setup#usb-troubles-on-linda-uol for issues with the built in asus we had in Lincoln.

**Comment by ToMadoRe** [comment]
Sorry for getting off-topic, but it's been very useful. The robot runs now even though there are still some problems with the USB interface and the ASUS. I will check that again tomorrow...

Thank you very much for the help.

**Comment by cdondrup** [comment]
You are very welcome. 
I will close this issue as solved because the original problem is and would ask you to open new issues for the other problems tomorrow in the according repositories.
