### ISSUE TITLE
Patroller fails to charge battery

### ISSUE THREAD

**Issue by hawesie** [strands-project/autonomous_patrolling#38]
It appears that when the patroller needs to charge the battery, something is preventing it from doing so. Instead of going to the station it repeatedly plans paths to all waypoints (visible on rviz) but then doesn't move. The full patroller log is at https://gist.github.com/hawesie/6296072 or in ~strands/.ros/log/2a049248-0a6c-11e3-acc5-843a4b7f1c04/ on bob.

**Comment by bfalacerda** [comment]
This is because CHARGE_BATTERY_TRESHOLD (which represents when the robot should choose go charge instead of patrolling a new point) in long_term_patroller.py needs to be greater or equal than LOW_BATTERY (which represents when the robot should give up going to a patrol point due to low battery) in monitor_states.py.

Otherwise, the POINT_CHOOSER state keeps trying to patrol a new point, but then the MONITORED_MOVE_BASE state machine for patrolling immediately outputs battery_low and the top level state machine keeps looping between these two states.

I'll take care of issue #35 tomorrow, and I'll make CHARGE_BATTERY_TRESHOLD equal to the LOW_BATTERY parameter plus a small constant. This will make the risk of wrongly defining these parameters disappear.

**Comment by hawesie** [comment]
Ah, I had the feeling I had probably screwed up the thresholds. Thanks!
