### ISSUE TITLE
Interface for external control

### ISSUE THREAD

**Issue by hawesie** [strands-project/autonomous_patrolling#42]
I'd like to have the option to generate the following behaviour in the patroller via method call: 
- [ ] pause execution (stopping the robot immediately) and then, optionally, resume such that the robot carries on heading to the previously selected waypoint, or leave it idle
- [ ] send the robot to an arbitrary pose, then leaving it idle there
- [ ] start patrolling from an idle

I plan to use these in a GUI for the robot.

**Comment by bfalacerda** [comment]
I'm going to create a monitor for the pause button and add it to the navigation state_machine. For now I'll only listen for a gamepad pause but I'll have it so we can easily add other ways to pause and restart the robot (from a web interface for example)

**Comment by marc-hanheide** [comment]
Reading this I wonder if you are using the current joystick node in your system where the pause button has the semantic to stop the motors and enable freerun. We always find the possibility to override the robot with the joystick very useful... Maybe I missed something though.

**Comment by bfalacerda** [comment]
I'm not sure I understand what you meant @marc-hanheide but from what I understand you're worried that I'm going to change the implementation of the pause button in the gamepad, which is not the case. I was a bit misleading in the previous comment, so let me clarify. What I'm going to add  is an on-demand preemption mechanism for move_base in the navigation state machine. The request for preemption can come from different sources (and I'll try to make the addition of new sources as straightforward as possible), the ones we've thought of until now are:
1. The external gui mentioned in this issue (that's why I added the comment here);
2. The gamepad, when a user wants to take over and use teleoperation (as we've been discussing in https://github.com/strands-project/scitos_apps/issues/37 we also still need to decide how/if we'll be using the mux for this purpose and see how these things connect). This is the one I'm going to implement now, and my plan is to preempt move_base when the dead man's switch is pressed (so the "pause" button I was referring to is the dead man's switch and I'll leave the more "failsafe" pause button as it is);
3. To deal with issue https://github.com/strands-project/strands_morse/issues/53 we'll also need to have the simulated robot standing still to avoid conflicts with the new objects spawned in the environment, so we can have the simulator using this feature to avoid having differences between the real robot and simulation implementations.

Does this answer to your comment, or were you making a different point?

**Comment by marc-hanheide** [comment]
No, that clearly goes in the right direction ;-) Seems to me again the issue we already started in https://github.com/strands-project/scitos_apps/issues/37, namely my lack of understanding how you guys plan to solve the arbitration. I was just worried that this here would again cause a change in the expected operation of existing components (namely the gamepad controller). If this is not the case, then we can postpone the discussion until we have the real one about arbitration, as @hawesie suggested somewhere in strands-management in the non-public. I still don't quite get the whole story, but that's merely my ignorance ;-) Keep going, I'm sure you guys have thought about this much more than I can grasp right now.

Only final comment: the dead-man switch is in our system not only used for "emergency interception", but also to simply show off the robot, while it runs, e.g. to show that one can move the head, blink, or even mess with the robot's navigation and see it recover...

**Comment by bfalacerda** [comment]
Yes, I just think this can be useful regardless of the outcome of that discussion, that's why I'm going ahead with it. All the functionalities of the dead man switch will remain the same, I'll be just subscribing to it and preempting the move_base action when it is pressed.

**Comment by bfalacerda** [comment]
Pull request #66 added a service call for pausing - resuming the patroller, by using:

`rosservice call /pause_resume_patroller`

Each call basically switches the patroller state from paused to running. With this you can use rviz (or the nav stack directly) to send the robot to another place. This navigation is just based on move_base, thus there's not monitoring and recovering from, for example, a bumper hit. That would be a bit more messy to add.

@hawesie, is this service call enough for the robot GUI? I think it ticks the 3 boxes you mentioned (though the navigation to an arbitrary pose is less robust)

**Comment by hawesie** [comment]
Yes, this looks good to me, thanks! Closed by #66.
