### ISSUE TITLE
The long term patroller cannot cope with a blocked route to waypoint

### ISSUE THREAD

**Issue by ghost** [strands-project/autonomous_patrolling#56]
When we ran the long_term_patroller today, it pretty much "failed" when an obstacle would block the only path to the next waypoint. It kept spinning around and moved back about 30cm after a spin. It didn't move on to another waypoint on the list. Seeing it like this felt like a failure to me to be honest. It didn't call for help, nor could it complete any of its possible task. 

Is this intended? I think spoke to @BFALacerda and you said that it would pick a new waypoint if it couldn't reach one.

**Comment by hawesie** [comment]
I think the spinning and moving is the move base recovery behaviour (it's trying to clear out its cost map).

**Comment by bfalacerda** [comment]
Yes, it's the recovery behaviours. The spinning is from move_base itself, and the move backwards is from the recovery state I implemented. The state machine will try 5 times until it gives up on a given point, so you need to wait a bit more to see a change in goal. When we have v2 as the master branch, I'm going to make some changes:
- Allow for dynamic reconfiguration of the max move base fails parameter (and other parameters that are not reconfigurable)
- Make the default value for  rotation recovery false, as it creates some extra bugs (see issues #39 and #27) and it doesn't really make a big difference - we can simply clear the costmap and not rotate afterwards
- Take out the drive backwards recovery behaviour I implemented, it's pretty dangerous to drive backwards in such an uncontrolled manner

**Comment by cdondrup** [comment]
The current stopping and slowing down behaviour to let humans pass uses dynamic reconfigure of the speed move_base uses. This leads to quite a high risk of omitting a goal because move_base just times out after a while if the robot does not move. This could be detected by looking at the feedback of the human_aware_planner_velocity action server to determine if the speed has been altered. But just going to a new place after a given amount of tries is no solution to that I'm afraid. I will have a look at how to best handle this before we integrate it into the standard behaviour.

I personally think that the moving backwards recovery in general is not a bad idea because sometimes the robot navigates itself into a corner it can't escape from (especially when using the carrot planner and the human_aware stuff), but I agree that the recovery rotation is useless and even detrimental in some cases.
Btw.: Have you ever tried setting the `penalize_negative_x` parameter of the dwa planner to true? Did not seem to have any effect on the planning when I tried it.

**Comment by bfalacerda** [comment]
Going a bit backwards is useful sometimes, but I've also seen the robot hitting a wall because of it... We'll probably need to test to see how it affects the number of move base / bumper failures.

I think I tried to change penalize_negative_x a while ago and nothing happened either, but I'm not sure of this

**Comment by cdondrup** [comment]
I agree, moving backwards after clearing the costmap could be fatal.

**Comment by bfalacerda** [comment]
Or before clearing, right now the recovery state is not using move_base, it's just publishing negative speeds do cmd_vel

**Comment by ghost** [comment]
I think this is indeed a very bad thing. Our robot almost fell over, because it was driving backwards, while the display pushed it forwards because it was touching the wall.

**Comment by bfalacerda** [comment]
I'll take it out this afternoon

**Comment by bfalacerda** [comment]
closing issues I think look solved to clean the repo's issue list. Please reopen if you fell further discussion is needed
