### ISSUE TITLE
Transferring this package into the suggested repository layout

### ISSUE THREAD

**Issue by cdondrup** [strands-project/autonomous_patrolling#8]
I think this is best be done by one of us: @BFALacerda @AlexanderHermans @ToMadoRe

**Comment by bfalacerda** [comment]
I'll look into it tomorrow, don't know if there will be problems with using the navigation stack in a catkin workspace. If there is, this might help:

http://answers.ros.org/question/57444/catkin-cant-find-move_base/

**Comment by nilsbore** [comment]
Me and @RaresAmbrus will also look at having some stuff transferred to 2d_navigation. If you only want to use the move base through a launch file, there are no problems with catkin.

**Comment by cdondrup** [comment]
@nilsbore using move base from a launch file is exactly what we would need. Let me know if you need any help with transferring it to the 2d_nav.

**Comment by nilsbore** [comment]
@cdondrup Allright, I will have a look at it now!

**Comment by kunzel** [comment]
Hi @cdondrup , Could you please follow a structure similar to pr2_navigation? I would be good to have the move_base config files in an independent package similar to pr2_navigation_config. This way we could use the same package for the real robot and the MORSE simulation.

**Comment by nilsbore** [comment]
@cdondrup , @kunzel Hi, I've begun looking at this now. We have altered the move base parameter files and written launch files for running it on the robot. We need to agree on a naming convention for the depth camera frame and the name of the topic. Right now, we use the frames and topics defined by the openni_launch package, that is camera_link for the frame and something like /camera/depth/points for the point cloud (it provides many data streams). Since we will use many cameras, this doesn't really make sense, it should probably be something like head_camera_link and head_camera_points to be more descriptive. What's your thought on this?

**Comment by nilsbore** [comment]
@kunzel We would have to use the same urdf file in both packages, which ties into what we wrote above. The one I used on the robot can be found in https://github.com/strands-project/scitos_mira/blob/master/src/scitos_description/scitosa5.urdf. This should probably be moved into scitos_common, following the pr2 organization. But again, we will have to agree on which naming to use for the tf tree.

**Comment by hawesie** [comment]
Yep, please move the URDF to scitos_common following the [PR2 structure](http://ros.org/wiki/pr2_common).

**Comment by nilsbore** [comment]
@kunzel @hawesie Ok, I'll create the package and move the urdf there, we can modify it from there to get the naming right.

**Comment by nilsbore** [comment]
@hawesie BTW, should it be private?

**Comment by hawesie** [comment]
No, public is fine for this.

**Comment by kunzel** [comment]
@nilsbore I am happy with any naming scheme for the topics as I can simply adapt the topic names in the simulator directly and or remap the topics in a launch file. I agree with you that we should pcik more sensible names for the topics. Maybe the best would be to align the naming with the URDF links?

**Comment by kunzel** [comment]
@nilsbore I'll move the URDF that you have used to scitos_common. So you can rely on this naming scheme in the beginning. Would this be fine for you? Or would you already use different names?

**Comment by nilsbore** [comment]
Hey, sorry that it's taking so long, I'm traveling today. I will rely on this naming scheme to begin with, which will allow me to upload the nav stack launch files directly.

**Comment by kunzel** [comment]
@nilsbore Now you can find the URDF in [scitos_common](https://github.com/strands-project/scitos_common). In particular, it is in the package scitos_description.

**Comment by nilsbore** [comment]
@kunzel Allright, I'm finally sitting on a train for a bit longer so I'll upload the packages now. I'll create a new package/repo scitos_2d_navigation_config with the move base parameters. Or should this go in scitos_common?

**Comment by kunzel** [comment]
@nilsbore yes create a package with this name please. It should not go in common.

**Comment by nilsbore** [comment]
ok, I think I got the idea, I'll create a package with that name inside the scitos_2d_navigation repo

**Comment by bfalacerda** [comment]
It seems that or we catkinize the dependencies which are not catkinized yet (move_base and smach) or we'll have to use rosbuild. I tried removing the dependencies from the package.xml and CMakeLists.txt but then I can't import them in the patroller.py file without providing the full path, e.g.:

sys.path.append("/opt/ros/groovy/stacks/executive_smach/smach/src")
import smach

Of course this is a bad option because it depends on where  ros is installed... Anyone is working on this or has an idea on how to it?

**Comment by hawesie** [comment]
The groovy-devel branch of smach should support catkin and rosmake in a hybrid way: https://github.com/ros/executive_smach/tree/groovy-devel

There is also a catkinised version of navigation: https://github.com/ros-planning/navigation/tree/groovy-devel-catkinized

I'm happy to work from these source dependencies if it's not too difficult.
