### ISSUE TITLE
Ignore charging waypoint while patrolling

### ISSUE THREAD

**Issue by cdondrup** [strands-project/autonomous_patrolling#94]
Observing Linda patrol got me worried about our charging waypoint. It is of course pretty close to the charging station and therefore also pretty close to the wall and two cupboards. I fear that at some point the planner will just steer her to close to one of these obstacles and she won't be able to recover. Would it be possible to make the first (or last) waypoint (or mark it in any arbitrary way) a charging waypoint to which she only goes when she wants to restart?
Don't know how the other think about that but I think that is a potential failure waiting to happen.

**Comment by bfalacerda** [comment]
the charging waypoint is the first one by default and is already being ignored by the point chooser: move base is only called with it as a goal when it's time to charge. If you witnessed the robot going to that area when it didn't want to charge, it's because move_base planned to go through it for some reason, but it wasn't its goal

**Comment by cdondrup** [comment]
I thought I read something about this before... 
We figured out why she is going to that point. This is what happens when you are supposed to use the waypoints we used to run the not-LTP-based patrol. In that file there is an undocking and a docking waypoint. So the undocking waypoint is ignored but she still goes to the docking waypoint because this the last one.
So please consider this an easily, successfully solved issue and thank you very much for your help :)

**Comment by bfalacerda** [comment]
my favourite type of issue :)
